# Generated by Django 5.1.2 on 2024-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('created_at_time', models.BigIntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('cause', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('invoice_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
