#
#version: '3'
#services:
#
#
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#
#
version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://yaya123:yaya123@db:5432/yaya123

  db:
    image: postgres
    environment:
      POSTGRES_DB: yaya123      # The name of your database
      POSTGRES_USER: yaya123    # The username for the database
      POSTGRES_PASSWORD: yaya123 # The password for the database
